### ISSUE TITLE
How can I make the TI-MVDR files?

### ISSUE THREAD

**Issue by hido710** [Andong-Li-speech/TaylorBeamformer#3]
Hi. Thanks for the code.
I wonder how to create a TI-MVDR file.
Is it a Delay-and-Sum approach or an Oracle MVDR approach?
And is there any public code to extract those files?

I look forward to your reply.
Have a good day :)

22/11/24 - completed by myself

**Comment by shenbuguanni** [comment]
> Hi. Thanks for the code. I wonder how to create a TI-MVDR file. Is it a Delay-and-Sum approach or an Oracle MVDR approach? And is there any public code to extract those files?
> 
> I look forward to your reply. Have a good day :)
> 
> 22/11/24 - completed by myself
Have you implemented TI-MVDR?
